finder:
  --exit-0: true
  --select-1: true
  --tiebreak: begin,index
  --height: 60%
  --cycle: true
  --preview-window: right:50%

.completion-base: &completion-base
  finder: &finder-base
    --nth: 3
  callback: awk '{ print $3 }' | tr '\n' ' '

.completion-multi: &completion-multi
  <<: *completion-base
  finder:
    <<: *finder-base
    --multi: true

.completion-git: &completion-git
  <<: *completion-base
  finder: &finder-git
    <<: *finder-base
    --preview: |-
      if [[ {2} != option ]]; then
        git show --color {3} | delta
      else
        printf "option: %s" {3}
      fi

.completion-docker-image: &completion-docker-image
  <<: *completion-base
  callback: awk '{ if($3 ~ /<none>/) { print $4 } else { print $3 } }' | tr '\n' ' '

.completion-docker-image-multi: &completion-docker-image-multi
  <<: *completion-docker-image
  finder:
    <<: *finder-base
    --multi: true

completions:
  #########################################################
  # Files and Directories
  #########################################################
  - description: file
    patterns:
      - ^\s*(bat|cat|delta|diff|grep|head|hexdump|hexyl|less|nvim|sed|tail|vim|vi)\s
      - (<|>>?)\s+\S*$
      - (?P<redirect>(<|>>?))(?P<query>\S*)$
    source: |-
      local dir="$(sed -E "s:^~/:$HOME/:; s:[^/]*\$::" <<<"${(Q)query}")"
      fd --color=always --hidden --type=f --follow . "${dir:-.}" 2>/dev/null | sed -E "s:$HOME/:~/:"
    finder:
      --multi: true
      --preview: sed -E "s:^~/:$HOME/:" <<<{} | xargs -d '\n' fzf-preview-file
    callback: <<<"$redirect$(sed 's/ /\\ /g' | tr '\n' ' ')"

  - description: file or directory
    patterns:
      - ^\s*(code|cp|ln|mmv|mv|open|rm|subl|trash|wslview)\s
    source: |-
      local dir="$(sed -E "s:^~/:$HOME/:; s:[^/]*\$::" <<<"${(Q)query}")"
      fd --color=always --hidden --follow . "${dir:-.}" 2>/dev/null | sed -E "s:$HOME/:~/:"
    finder:
      --multi: true
      --preview: sed -E "s:^~/:$HOME/:" <<<{} | xargs -d '\n' fzf-preview-file
    callback: sed 's/ /\\ /g' | tr '\n' ' '

  - description: directory
    patterns:
      - ^\s*(cd|la|ll|ls|tree)\s
      - ^\s*go\s+test\s
    source: |-
      local dir="$(sed -E "s:^~/:$HOME/:; s:[^/]*\$::" <<<"${(Q)query}")"
      fd --color=always --hidden --type=d --follow . "${dir:-.}" 2>/dev/null | sed -E "s:$HOME/:~/:"
    finder:
      --preview: sed -E "s:^~/:$HOME/:" <<<{} | xargs -d '\n' fzf-preview-file
    callback: sed -E 's/ /\\ /g; s:/?$:/:'

  #########################################################
  # asdf
  #########################################################
  - description: asdf
    patterns:
      - ^\s*asdf\s
    source: |-
      "$QWY_SCRIPT_PATH/options.zsh" "asdf/subcommands" '󰘳' "command" "yellow"
      "$QWY_SCRIPT_PATH/options.zsh" "asdf/options" '󰈻' "option" "blue"
    <<: *completion-base

  #########################################################
  # cURL
  #########################################################
  - description: curl
    patterns:
      - ^\s*curl\s
    source: |-
      <"$QWY_CONFIG_HOME/snippets/curl/snippet.txt"
    finder:
      --multi: true
    callback: tr '\n' ' '

  #########################################################
  # Make
  #########################################################
  - description: make
    patterns:
      - ^\s*make\s
    source: |-
      rg --line-number '^[0-9A-Z_a-z\-]+:' Makefile 2>/dev/null | tr ':' '\t'
    finder:
      --delimiter: '\t'
      --with-nth: 2
      --multi: true
      --preview: |-
        local line={1} n=10 start="\$(( line > n ? line - n : 1 ))"
        bat --color=always --language=Makefile --highlight-line="\$line" --line-range="\$start:" Makefile
    callback: cut -f 2

  #########################################################
  # Docker
  #########################################################
  - description: docker-build
    patterns:
      - ^\s*docker\s+build\s
    source: |-
      "$QWY_SCRIPT_PATH/options.zsh" "docker/build-options" '󰈻' "option" "blue"
    <<: *completion-base

  - description: docker-rm
    patterns:
      - ^\s*docker\s+rm\s
    source: |-
      "$QWY_SCRIPT_PATH/docker-ps.zsh"
    <<: *completion-multi

  - description: docker-rmi
    patterns:
      - ^\s*docker\s+rmi\s
    source: |-
      "$QWY_SCRIPT_PATH/docker-images.zsh"
    <<: *completion-docker-image-multi

  - description: docker-run
    patterns:
      - ^\s*docker\s+run\s
    source: |-
      "$QWY_SCRIPT_PATH/docker-images.zsh"
      "$QWY_SCRIPT_PATH/options.zsh" "docker/run-options" '󰈻' "option" "blue"
    <<: *completion-docker-image

  - description: docker
    patterns:
      - ^\s*docker\s+\S*$
    source: |-
      "$QWY_SCRIPT_PATH/options.zsh" "docker/subcommands" '󰘳' "command" "yellow"
      "$QWY_SCRIPT_PATH/options.zsh" "docker/aliases" '󰏪' "alias" "red"
      "$QWY_SCRIPT_PATH/options.zsh" "docker/options" '󰈻' "option" "blue"
    <<: *completion-base

  #########################################################
  # Git
  #########################################################

  - description: git-<ref>
    patterns:
      - ^\s*git\s+(bisect\s+start|graph|log|merge|rebase|revert|show)\s
    source: |-
      "$QWY_SCRIPT_PATH/git-local-branches.zsh"
      "$QWY_SCRIPT_PATH/git-remote-branches.zsh"
      "$QWY_SCRIPT_PATH/git-tags.zsh"
      "$QWY_SCRIPT_PATH/git-commits.zsh"
    <<: *completion-git

  - description: git-branch
    patterns:
      - ^\s*git\s+branch\s
    source: |-
      "$QWY_SCRIPT_PATH/git-local-branches.zsh"
    <<: *completion-git

  - description: git-cherry-pick
    patterns:
      - ^\s*git\s+cherry-pick\s
    source: |-
      "$QWY_SCRIPT_PATH/git-commits.zsh" --all
      "$QWY_SCRIPT_PATH/options.zsh" "git/cherry-pick-options" '󰈻' "option" "blue"
    <<: *completion-git
    finder:
      <<: *finder-git
      --multi: true

  - description: git-commit --fixup
    patterns:
      - ^\s*git\s+commit\s+(\S+\s+)*--fixup\s+\S*$
      - ^\s*git\s+commit\s+(\S+\s+)*(?P<fixup>--fixup=)(?P<query>\S*)$
    source: |-
      "$QWY_SCRIPT_PATH/git-commits.zsh" --all
    <<: *completion-git
    callback: <<<"$fixup$(awk '{ print $3 }' | tr '\n' ' ')"

  - description: git-diff
    patterns:
      - ^\s*git\s+(df|diff)\s
    source: |-
      "$QWY_SCRIPT_PATH/git-local-branches.zsh"
      "$QWY_SCRIPT_PATH/git-remote-branches.zsh"
      "$QWY_SCRIPT_PATH/git-tags.zsh"
      "$QWY_SCRIPT_PATH/git-commits.zsh"
      "$QWY_SCRIPT_PATH/options.zsh" "git/diff-options" '󰈻' "option" "blue"
    <<: *completion-git

  - description: git-fetch
    patterns:
      - ^\s*git\s+fetch\s
    source: |-
      git remote
    finder:
      --preview: git remote get-url {}
    callback: awk '{ print $1 }' | tr '\n' ' '

  - description: git-push <remote> <branch>
    patterns:
      - ^\s*git\s+push\s+(-\S*\s+)*[^-]\S*\s
    source: |-
      "$QWY_SCRIPT_PATH/git-local-branches.zsh"
      "$QWY_SCRIPT_PATH/git-remote-branches.zsh"
      "$QWY_SCRIPT_PATH/git-tags.zsh"
    <<: *completion-git
    callback: awk '{ print $3 }' | sed 's:^origin/::'

  - description: git-push <remote>
    patterns:
      - ^\s*git\s+push\s+(-\S*\s+)*([^-]\S*)?$
    source: |-
      git remote
    finder:
      --preview: git remote get-url {}
    callback: tr '\n' ' '

  - description: git-reset
    patterns:
      - ^\s*git\s+reset\s
    source: |-
      "$QWY_SCRIPT_PATH/options.zsh" "git/reset-options" '󰈻' "option" "blue"
      "$QWY_SCRIPT_PATH/git-local-branches.zsh"
      "$QWY_SCRIPT_PATH/git-remote-branches.zsh"
      "$QWY_SCRIPT_PATH/git-tags.zsh"
      "$QWY_SCRIPT_PATH/git-commits.zsh"
    <<: *completion-git
    callback: awk '{ print $3 }' | sed 's:^origin/::'

  - description: git-switch
    patterns:
      - ^\s*git\s+switch\s
    source: |-
      "$QWY_SCRIPT_PATH/git-local-branches.zsh"
      "$QWY_SCRIPT_PATH/git-remote-branches.zsh"
      "$QWY_SCRIPT_PATH/git-tags.zsh"
      "$QWY_SCRIPT_PATH/git-commits.zsh"
    <<: *completion-git
    callback: awk '{ print $3 }' | sed 's:^origin/::'

  - description: git-tag
    patterns:
      - ^\s*git\s+tag\s
    source: |-
      "$QWY_SCRIPT_PATH/git-tags.zsh"
      "$QWY_SCRIPT_PATH/options.zsh" "git/tag-options" '󰈻' "option" "blue"
    <<: *completion-git

  - description: git-user
    patterns:
      - ^\s*git\s+user\s+\S*$
    source: |-
      git users | sed -E 's/:\s*/\t/'
    callback: awk '{ print $1 }'

  - description: git
    patterns:
      - ^\s*git\s\S*$
    source: |-
      "$QWY_SCRIPT_PATH/options.zsh" "git/subcommands" '󰘳' "command" "yellow"
      "$QWY_SCRIPT_PATH/git-aliases.zsh"
      "$QWY_SCRIPT_PATH/git-tools.zsh"
      "$QWY_SCRIPT_PATH/options.zsh" "git/options" '󰈻' "option" "blue"
    <<: *completion-base

  #########################################################
  # NPM
  #########################################################
  - description: npm-run
    patterns:
      - ^\s*(npm|pnpm)\s+run\s+\S*$
    source: |-
      "$QWY_SCRIPT_PATH/npm-scripts.zsh"
    <<: *completion-base

  - description: npm
    patterns:
      - ^\s*npm\s+\S*$
    source: |-
      "$QWY_SCRIPT_PATH/options.zsh" "npm/subcommands" '󰘳' "command" "yellow"
    <<: *completion-base

  #########################################################
  # Deno
  #########################################################
  - description: deno-task
    patterns:
      - ^\s*deno\s+task\s+\S*$
    source: |-
      "$QWY_SCRIPT_PATH/deno-tasks.zsh"
    <<: *completion-base

  - description: deno
    patterns:
      - ^\s*deno\s+\S*$
    source: |-
      "$QWY_SCRIPT_PATH/options.zsh" "deno/subcommands" '󰘳' "command" "yellow"
    <<: *completion-base

  #########################################################
  # Tmux
  #########################################################
  - description: tmux
    patterns:
      - ^\s*tmux\s+\S*$
    source: |-
      "$QWY_SCRIPT_PATH/options.zsh" "tmux/subcommands" '󰘳' "command" "yellow"
      "$QWY_SCRIPT_PATH/options.zsh" "tmux/options" '󰈻' "option" "blue"
    <<: *completion-base
