#!/usr/bin/env bash
add-apt-repository ppa:git-core/ppa &&
apt-get update && apt-get upgrade &&
apt-get install -y \
    automake \
    build-essential \
    colordiff \
    git \
    gpg \
    libssl-dev \
    neovim \
    python3 \
    python3-pip \
    tmux \
    unzip \
    wget \
    zip \
    zsh
