#!/usr/bin/env bash
apt-get update && apt-get upgrade &&
add-apt-repository ppa:git-core/ppa &&
apt-get install \
    build-essential \
    zsh \
    git \
    neovim \
    tmux \
    wget \
    unzip \
    zip \
    colordiff \
    gpg \
    python \
    python-pip \
    python3 \
    python3-pip
