#!/usr/bin/env bash
add-apt-repository ppa:git-core/ppa &&
apt-get update && apt-get upgrade &&
apt-get install -y \
    automake \
    build-essential \
    zsh \
    git \
    neovim \
    tmux \
    wget \
    unzip \
    zip \
    colordiff \
    gpg \
    python3 \
    python3-pip
