- description: file
  regexp-left: ^\s*(?P<cmd>(bat|cat|e|grep|head|hexdump|less|nvim|sed|tail|vim|view|vi))(\s+|$)(?P<args>((\\ |[^\\\s])+\s+)*)(?P<query>(\\ |[^\\\s])*)$
  cmd-groups:
    - stmt: fd --color=always --type=f
      after: sed 's/ /\\ /g' | tr '\n' ' ' | sed 's/ $//'
  fuzzy-finder-cmd: fzf --exit-0 --select-1 --multi --height="40%" --preview="fzf-preview-file {}" --preview-window="right:50%" --query=<query> || echo <query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: file or directory
  regexp-left: ^\s*(?P<cmd>(cp|mv|rm))(\s+|$)(?P<args>((\\ |[^\\\s])+\s+)*)(?P<query>(\\ |[^\\\s])*)$
  cmd-groups:
    - stmt: fd --color=always
      after: sed 's/ /\\ /g'
  fuzzy-finder-cmd: fzf --exit-0 --select-1 --height="40%" --preview="fzf-preview-file {}" --preview-window="right:50%" --query=<query> || echo <query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: directory
  regexp-left: ^\s*(?P<cmd>(cd|la|ll|ls|tree))(\s+|$)(?P<query>(\\ |[^\\\s])*)$
  cmd-groups:
    - stmt: fd --color=always --type=d
      after: sed 's/ /\\ /g'
  fuzzy-finder-cmd: fzf --exit-0 --select-1 --height="40%" --preview="fzf-preview-directory {}" --preview-window="right:50%" --query=<query> || echo <query>
  buffer-left: '<cmd> '
  buffer-right: '[]'

- description: fallthrough
  buffer-left: '[]'
  buffer-right: '[]'
