### File and Directories
- description: file
  regexp-left: ^\s*(?P<cmd>(bat|cat|e|grep|head|hexdump|less|nvim|sed|tail|vim|view|vi))(\s+|$)(?P<args>((\\ |[^\\\s])+\s+)*)(?P<query>(\\ |[^\\\s])*)$
  cmd-groups:
    - stmt: fd --color=always --hidden --type=f
      after: |
        sed 's/ /\\ /g' | # Escape spaces
          tr '\n' ' '   | # Replace EOL
          sed 's/ $//'    # Remove trailing spaces
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --multi \
      --preview="fzf-preview-file {}" \
      --query=<query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: file or directory
  regexp-left: ^\s*(?P<cmd>(cp|mv|rm))(\s+|$)(?P<args>((\\ |[^\\\s])+\s+)*)(?P<query>(\\ |[^\\\s])*)$
  cmd-groups:
    - stmt: fd --color=always --hidden
      after: sed 's/ /\\ /g' # Escape spaces
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --preview="fzf-preview-file {}" \
      --query=<query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: directory
  regexp-left: ^\s*(?P<cmd>(cd|la|ll|ls|tree))(\s+|$)(?P<query>(\\ |[^\\\s])*)$
  cmd-groups:
    - stmt: fd --color=always --hidden --type=d
      after: sed -E 's/ /\\ /g; s,/?$,/,' # Escape spaces and add trailing slash
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --preview="fzf-preview-directory {}" \
      --query=<query>
  buffer-left: '<cmd> '
  buffer-right: '[]'

### Git
- description: git-switch
  regexp-left: ^\s*(?P<cmd>(git|g))\s+(?P<subcmd>(switch|sw))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/git-local-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-remote-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-tags.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-commits.zsh"'
      after: awk '{ print $3 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --nth=3 \
      --tiebreak='begin,length' \
      --preview="echo {} | awk '{ print \$3 }' | xargs -r git show --color | delta" \
      --query=<query>
  buffer-left: '<cmd> <subcmd> <args>'
  buffer-right: '[]'

- description: git
  regexp-left: ^\s*(?P<cmd>(git|g))(\s+|$)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/git-subcommands.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-aliases.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-options.zsh"'
      after: awk '{ printf "%s ", $3 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --nth=3 \
      --tiebreak='begin,length' \
      --query=<query>
  buffer-left: '<cmd> '
  buffer-right: '[]'

### Fallthrough
- description: fallthrough
  buffer-left: '[]'
  buffer-right: '[]'
