### File and Directories
- description: file
  regexp-left: ^\s*(?P<cmd>(bat|cat|e|grep|head|hexdump|hexyl|less|nvim|sed|tail|vim|view|vi))(\s+|$)(?P<args>((\\.|[^\\\s])+\s+)*)(?P<query>(\\.|[^\\\s])*)$
  cmd-groups:
    - stmt: fd --color=always --hidden --type=f
      after: sed 's/ /\\ /g' | paste -s -d ' ' - # Escape spaces and replace EOL
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --multi \
      --preview="fzf-preview-file {}" \
      --query=<query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: file or directory
  regexp-left: ^\s*(?P<cmd>(cp|ln|mv|rm))(\s+|$)(?P<args>((\\.|[^\\\s])+\s+)*)(?P<query>(\\.|[^\\\s])*)$
  cmd-groups:
    - stmt: fd --color=always --hidden
      after: sed 's/ /\\ /g' # Escape spaces
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --preview="fzf-preview-file {}" \
      --query=<query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: directory
  regexp-left: ^\s*(?P<cmd>(cd|la|ll|ls|tree))(\s+|$)(?P<query>(\\.|[^\\\s])*)$
  cmd-groups:
    - stmt: fd --color=always --hidden --type=d
      after: sed -E 's/ /\\ /g; s,/?$,/,' # Escape spaces and add trailing slash
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --preview="fzf-preview-directory {}" \
      --query=<query>
  buffer-left: '<cmd> '
  buffer-right: '[]'

### Fallthrough
- description: fallthrough
  buffer-left: '[]'
  buffer-right: '[]'
