- description: file
  regexp-left: ^\s*(?P<cmd>(bat|cat|e|grep|head|hexdump|less|nvim|sed|tail|vim|view|vi))(\s+|$)(?P<args>((\\ |[^\\\s])+\s+)*)(?P<query>(\\ |[^\\\s])*)$
  cmd-groups:
    - stmt: fd --color=always --type=f
      after: sed 's/ /\\ /g' | tr '\n' ' ' | sed 's/ $//'
  fuzzy-finder-cmd: fzf --exit-0 --select-1 --multi --height="40%" --preview="fzf-preview-file {}" --preview-window="right:50%" --query=<query> || echo <query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: file or directory
  regexp-left: ^\s*(?P<cmd>(cp|mv|rm))(\s+|$)(?P<args>((\\ |[^\\\s])+\s+)*)(?P<query>(\\ |[^\\\s])*)$
  cmd-groups:
    - stmt: fd --color=always
      after: sed 's/ /\\ /g'
  fuzzy-finder-cmd: fzf --exit-0 --select-1 --height="40%" --preview="fzf-preview-file {}" --preview-window="right:50%" --query=<query> || echo <query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: directory
  regexp-left: ^\s*(?P<cmd>(cd|la|ll|ls|tree))(\s+|$)(?P<query>(\\ |[^\\\s])*)$
  cmd-groups:
    - stmt: fd --color=always --type=d
      after: sed 's/ /\\ /g'
  fuzzy-finder-cmd: (fzf --exit-0 --select-1 --height="40%" --preview="fzf-preview-directory {}" --preview-window="right:50%" --query=<query> | sed -E 's:/?$:/:'; (( ! ${pipestatus[1]} ))) || echo <query>
  buffer-left: '<cmd> '
  buffer-right: '[]'

- description: git
  regexp-left: ^\s*(?P<cmd>(git|g))(\s+|$)(?P<query>\S*)?$
  cmd-groups:
    - stmt: "%git% | sed -E 's/^/\x1b[33m\uf526 command\x1b[m\\t/g'"
      after: awk '{ print $3 }'
    - stmt: "%git-opts% | sed -E 's/^/\x1b[34m\uf993 option\x1b[m\\t/g'"
      after: awk '{ print $3 }'
  fuzzy-finder-cmd: sed -E 's/ -- (.*)/\x1b[38;5;65m\1\x1b[m/g' | fzf --exit-0 --select-1 --height="40%" --tiebreak=begin,length --tabstop=4 --query=<query> || echo _ _ <query>
  buffer-left: '<cmd> '
  buffer-right: '[]'

- description: fallthrough
  buffer-left: '[]'
  buffer-right: '[]'
