- description: curl
  regexp-left: ^\s*(?P<cmd>curl\s+(\S+\s+)*)$
  cmd-groups:
    - stmt: cat "$PMY_CONFIG_HOME/snippets/curl/snippet.txt"
      after: tr '\n' ' '
  fuzzy-finder-cmd: >
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}"
    --multi
  buffer-left: '<cmd>'
  buffer-right: '[]'
