- description: docker-build
  regexp-left: ^\s*(?P<cmd>(docker|dok))\s+(?P<subcmd>(build))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "docker/build-options" "\uf73a" "option" "blue"'
      after: awk '{ printf "%s ", $3 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --nth=3 \
      --query=<query>
  buffer-left: '<cmd> <subcmd> <args>'
  buffer-right: '[]'

- description: docker-run
  regexp-left: ^\s*(?P<cmd>(docker|dok))\s+(?P<subcmd>(ri|rrmi|rrm|run))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/docker-images.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "docker/run-options" "\uf73a" "option" "blue"'
      after: awk '{ printf "%s ", $3 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --nth=3 \
      --query=<query>
  buffer-left: '<cmd> <subcmd> <args>'
  buffer-right: '[]'

- description: docker
  regexp-left: ^\s*(?P<cmd>(docker|dok))(\s+|$)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "docker/subcommands" "\ufb32" "command" "yellow"'
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "docker/aliases" "\uf8e9" "alias" "red"'
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "docker/options" "\uf73a" "option" "blue"'
      after: awk '{ printf "%s ", $3 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --nth=3 \
      --query=<query>
  buffer-left: '<cmd> '
  buffer-right: '[]'
