- description: git-branch
  regexp-left: ^\s*(?P<cmd>git\s+(branch))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/git-local-branches.zsh"'
      after: awk '{ print $3 }'
  fuzzy-finder-cmd: >
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}"
    --nth=3
    --query=<query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: git-cherry-pick
  regexp-left: ^\s*(?P<cmd>git\s+(cherry-pick))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/git-commits.zsh" --all'
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "git/cherry-pick-options" "\uf73a" "option" "blue"'
      after: awk '{ print $3 }' | tr '\n' ' '
  fuzzy-finder-cmd: >
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}"
    --multi
    --nth=3
    --query=<query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: git-diff
  regexp-left: ^\s*(?P<cmd>git\s+(df|diff))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/git-local-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-remote-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-tags.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-commits.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "git/diff-options" "\uf73a" "option" "blue"'
      after: awk '{ print $3 }'
  fuzzy-finder-cmd: >
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}"
    --nth=3
    --query=<query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: git-fetch
  regexp-left: ^\s*(?P<cmd>git\s+(fetch))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: git remote
      after: awk '{ print $1 }'
  fuzzy-finder-cmd: >
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}"
    --preview="git remote get-url {}"
    --query=<query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: git-log
  regexp-left: ^\s*(?P<cmd>git\s+(graph|log))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/git-local-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-remote-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-tags.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-commits.zsh"'
      after: awk '{ print $3 }'
  fuzzy-finder-cmd: >
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}"
    --nth=3
    --query=<query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: git-rebase
  regexp-left: ^\s*(?P<cmd>git\s+(rebase))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/git-local-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-remote-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-tags.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-commits.zsh"'
      after: awk '{ print $3 }'
  fuzzy-finder-cmd: >
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}"
    --nth=3
    --query=<query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: git-reset
  regexp-left: ^\s*(?P<cmd>git\s+(reset))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/git-local-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-remote-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-tags.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-commits.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "git/diff-options" "\uf73a" "option" "blue"'
      after: awk '{ print $3 }'
  fuzzy-finder-cmd: >
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}"
    --nth=3
    --query=<query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: git-switch
  regexp-left: ^\s*(?P<cmd>git\s+(merge|rebase|switch))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/git-local-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-remote-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-tags.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-commits.zsh"'
      after: awk '{ print $3 }' | sed 's|^origin/||'
  fuzzy-finder-cmd: >
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}"
    --nth=3
    --preview="echo {} | awk '{ print \$3 }' | xargs -r git show --color | delta"
    --query=<query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: git-tag
  regexp-left: ^\s*(?P<cmd>git\s+(tag))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/git-tags.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "git/tag-options" "\uf73a" "option" "blue"'
      after: awk '{ print $3 }'
  fuzzy-finder-cmd: >
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}"
    --nth=3
    --preview="echo {} | awk '{ print \$3 }' | xargs -r git show --color | delta"
    --query=<query>
  buffer-left: '<cmd> <args>'
  buffer-right: '[]'

- description: git-user
  regexp-left: ^\s*(?P<cmd>git\s+(user))(\s+|$)(?P<query>\S*)$
  cmd-groups:
    - stmt: git users | sed -E 's/:\s*/\t/'
      after: awk '{ print $1 }'
  fuzzy-finder-cmd: >
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}"
    --query=<query>
  buffer-left: '<cmd> '
  buffer-right: '[]'

- description: git
  regexp-left: ^\s*(?P<cmd>git)(\s+|$)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "git/subcommands" "\ufb32" "command" "yellow"'
    - stmt: '"$PMY_SCRIPT_PATH/git-aliases.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-tools.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "git/options" "\uf73a" "option" "blue"'
      after: awk '{ printf "%s ", $3 }'
  fuzzy-finder-cmd: >
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}"
    --nth=3
    --query=<query>
  buffer-left: '<cmd> '
  buffer-right: '[]'
