- description: git-diff
  regexp-left: ^\s*(?P<cmd>(git|g))\s+(?P<subcmd>(dfs|df|diffs|diff|stat))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/git-local-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-remote-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-tags.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-commits.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "git/diff-options" "\uf73a" "option" "blue"'
      after: awk '{ print $3 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --nth=3 \
      --query=<query>
  buffer-left: '<cmd> <subcmd> <args>'
  buffer-right: '[]'

- description: git-fetch
  regexp-left: ^\s*(?P<cmd>(git|g))\s+(?P<subcmd>(fetch|f))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: git remote
      after: awk '{ print $1 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --preview="git remote get-url {}" \
      --query=<query>
  buffer-left: '<cmd> <subcmd> <args>'
  buffer-right: '[]'

- description: git-switch
  regexp-left: ^\s*(?P<cmd>(git|g))\s+(?P<subcmd>(switch|sw))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/git-local-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-remote-branches.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-tags.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/git-commits.zsh"'
      after: awk '{ print $3 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --nth=3 \
      --preview="echo {} | awk '{ print \$3 }' | xargs -r git show --color | delta" \
      --query=<query>
  buffer-left: '<cmd> <subcmd> <args>'
  buffer-right: '[]'

- description: git-user
  regexp-left: ^\s*(?P<cmd>(git|g))\s+(?P<subcmd>(user))(\s+|$)(?P<query>\S*)$
  cmd-groups:
    - stmt: git users | sed -E 's/:\s*/\t/'
      after: awk '{ print $1 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --query=<query>
  buffer-left: '<cmd> <subcmd> '
  buffer-right: '[]'

- description: git
  regexp-left: ^\s*(?P<cmd>(git|g))(\s+|$)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "git/subcommands" "\ufb32" "command" "yellow"'
    - stmt: '"$PMY_SCRIPT_PATH/git-aliases.zsh"'
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "git/options" "\uf73a" "option" "blue"'
      after: awk '{ printf "%s ", $3 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --nth=3 \
      --query=<query>
  buffer-left: '<cmd> '
  buffer-right: '[]'
