- description: npm-run
  regexp-left: ^\s*(?P<cmd>(npm))\s+(?P<subcmd>(run))(\s+|$)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/npm-scripts.zsh"'
      after: awk '{ print $3 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --nth=3 \
      --query=<query>
  buffer-left: '<cmd> <subcmd> '
  buffer-right: '[]'

- description: npm
  regexp-left: ^\s*(?P<cmd>(npm))(\s+|$)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "npm/subcommands" "\ufb32" "command" "yellow"'
      after: awk '{ printf "%s ", $3 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --nth=3 \
      --query=<query>
  buffer-left: '<cmd> '
  buffer-right: '[]'
