- description: t-switch
  regexp-left: ^\s*(?P<cmd>(t))\s+(?P<subcmd>(switch|sw))(\s+|$)(?P<query>\S*)$
  cmd-groups:
    - stmt: tmux list-sessions -F "#S"
      after: cat
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --query=<query>
  buffer-left: '<cmd> <subcmd> '
  buffer-right: '[]'

- description: t-kill
  regexp-left: ^\s*(?P<cmd>(t))\s+(?P<subcmd>(kill|k))(\s+|$)(?P<args>(\S+\s+)*)(?P<query>\S*)$
  cmd-groups:
    - stmt: tmux list-sessions -F "#S"
      after: tr '\n' ' '
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --multi \
      --query=<query>
  buffer-left: '<cmd> <subcmd> <args>'
  buffer-right: '[]'

- description: t
  regexp-left: ^\s*(?P<cmd>(t))(\s+|$)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "t/subcommands" "\ufb32" "command" "yellow"'
      after: awk '{ print $3 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --nth=3 \
      --query=<query>
  buffer-left: '<cmd> '
  buffer-right: '[]'
