- description: t
  regexp-left: ^\s*(?P<cmd>(tmux))(\s+|$)(?P<query>\S*)$
  cmd-groups:
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "tmux/subcommands" "\ufb32" "command" "yellow"'
    - stmt: '"$PMY_SCRIPT_PATH/options.zsh" "tmux/options" "\uf73a" "option" "blue"'
      after: awk '{ print $3 }'
  fuzzy-finder-cmd: |
    "${(z)PMY_FUZZY_FINDER_DEFAULT_CMD}" \
      --nth=3 \
      --query=<query>
  buffer-left: '<cmd> '
  buffer-right: '[]'
