# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ";mail"
    replace: "ryoga_314@yahoo.com"

  - trigger: ";gmail"
    replace: "eial5q265e5@gmail.com"

  - trigger: ";id"
    replace: "Ryooooooga"

  - trigger: ";gh"
    replace: "github.com"

  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
