abbrevs:
  #########################################################
  # cd
  #########################################################

  # cd
  - name: --
    abbr: --
    snippet: popd

  - name: cd
    abbr-pattern: (\.\.|/)$
    snippet: cd $abbr
    evaluate: true
    if: '[[ -z "$RBUFFER" ]]'

  - name: cd -
    abbr: "-"
    snippet: popd
    action: replace-all
    global: true
    context: ^cd\s+\S+$

  - name: jj
    abbr: jj
    snippet: cd ${$(git rev-parse --show-cdup 2>/dev/null):-./}{}
    evaluate: true

  #########################################################
  # Editor
  #########################################################

  - name: e^M
    abbr: e
    snippet: |-
      $(
        local files="$(
          fd -0 --hidden --color=always --type=f |
          fzf --read0 --print0 --exit-0 --multi --preview='fzf-preview-file {}' --preview-window='right:60%'
        )"
        (( ${#files} )) && <<<"${EDITOR} ${(q@)${(0)files}}"
      )
    evaluate: true
    cursor: null
    if: |-
      [[ "$KEYS" == $'\r' ]] && [[ -z "$RBUFFER" ]]

  - name: e
    abbr: e
    snippet: ${EDITOR}
    evaluate: true

  #########################################################
  # CMake
  #########################################################

  - name: cmkb
    abbr: cmkb
    snippet: cmake --build $(git rev-parse --show-cdup 2>/dev/null)build -j
    evaluate: true

  - name: cmkd
    abbr: cmkd
    snippet: cmake -DCMAKE_BUILD_TYPE=Debug -B $(git rev-parse --show-cdup 2>/dev/null)build
    evaluate: true

  - name: cmkrel
    abbr: cmkrel
    snippet: cmake -DCMAKE_BUILD_TYPE=Release -B $(git rev-parse --show-cdup 2>/dev/null)build
    evaluate: true

  - name: cmkt
    abbr: cmkt
    snippet: ctest -V --test-dir $(git rev-parse --show-cdup 2>/dev/null)build
    evaluate: true

  #########################################################
  # lazygit
  #########################################################

  # lazygit
  - name: lg
    abbr: lg
    snippet: lazygit

  #########################################################
  # Terraform
  #########################################################

  # terraform
  - name: tf
    abbr: tf
    snippet: terraform

  - name: terraform plan
    abbr: p
    snippet: plan
    global: true
    context: ^terraform\s

  - name: terraform apply
    abbr: ap
    snippet: apply
    global: true
    context: ^terraform\s

  #########################################################
  # Misc
  #########################################################

  # awk
  - name: .N
    abbr-pattern: ^\.(?<n>\d+)$
    snippet: awk '{ print \$$n }'
    evaluate: true

  # editor
  - name: view
    abbr: view
    snippet: ${EDITOR} -R
    evaluate: true

  # python
  - name: python
    abbr: python
    snippet: python3

  - name: pip
    abbr: pip
    snippet: pip3

  - name: python -v
    abbr: -v
    snippet: -V
    global: true
    context: ^(python3?|pip3?)\s

  # tee
  - name: teep
    abbr: teep
    snippet: tee >(pp)

  # date
  - name: yyyymmdd
    abbr: yyyymmdd
    snippet: $(date "+%Y%m%d")
    evaluate: true
    global: true

  - name: yyyy-mm-dd
    abbr: yyyy-mm-dd
    snippet: $(date "+%Y-%m-%d")
    evaluate: true
    global: true

  - name: yyyy/mm/dd
    abbr: yyyy/mm/dd
    snippet: $(date "+%Y/%m/%d")
    evaluate: true
    global: true

  # make
  - name: make
    abbr: make
    snippet: make -j

  # mkdir
  - name: mkdir
    abbr: mkdir
    snippet: mkdir -p

  - name: mkcd DIR
    abbr-pattern: .+
    snippet: mkdir -p $abbr && cd $abbr
    action: replace-all
    evaluate: true
    global: true
    context: ^mkcd\s

  # bat
  - name: batman
    abbr: batman
    snippet: bat -p -lman

  # hgrep
  - name: hg
    abbr: hg
    snippet: hgrep

  # trash
  - name: trash
    abbr: rm
    snippet: trash
    if: (( ${+commands[trash]} ))

  # zouch
  - name: zouch
    abbr: zouch
    snippet: zouch -r

  # coreutils
  - name: cp
    abbr: cp
    snippet: cp -ri

  - name: mv
    abbr: mv
    snippet: mv -i

  - name: rm
    abbr: rm
    snippet: rm -ri

  - name: tailf
    abbr: tailf
    snippet: tail -f

  # java
  - name: java -v
    abbr: -v
    snippet: -version
    global: true
    context: ^java\s

  # macOS
  - name: chrome
    abbr: chrome
    snippet: open -a 'Google Chrome'
    if: '[[ "$OSTYPE" =~ darwin ]]'

  # WSL
  - name: wslview
    abbr: open
    snippet: wslview
    if: (( ${+commands[wslview]} ))
