abbrevs:
  # cd
  - name: --
    abbr: --
    snippet: cd -

  - name: ..
    abbr: ..
    snippet: cd ..

  - name: ../..
    abbr: ../..
    snippet: cd ../..

  - name: ../../..
    abbr: ../../..
    snippet: cd ../../..

  - name: ..2
    abbr: ..2
    snippet: cd ../..

  - name: ..3
    abbr: ..3
    snippet: cd ../../..

  # git
  - name: git
    abbr: g
    snippet: git

  # git add
  - name: git add -vA
    abbr: aa
    snippet: add -vA
    global: true
    context: '^git\s'

  - name: git add -i
    abbr: ai
    snippet: add -i
    global: true
    context: '^git\s'

  # git branch
  - name: git branch
    abbr: b
    snippet: branch
    global: true
    context: '^git\s'

  # git commit
  - name: git commit
    abbr: c
    snippet: commit
    global: true
    context: '^git\s'

  - name: git commit -m
    abbr: cm
    snippet: commit -m
    global: true
    context: '^git\s'

  # git cherry-pick
  - name: git cherry-pick
    abbr: cp
    snippet: cherry-pick
    global: true
    context: '^git\s'

  # git diff
  - name: git diff --stat
    abbr: st
    snippet: diff --stat
    global: true
    context: '^git\s'

  - name: git diff --stat
    abbr: stat
    snippet: diff --stat
    global: true
    context: '^git\s'

  - name: git diff --stat --staged
    abbr: stats
    snippet: diff --stat --staged
    global: true
    context: '^git\s'

  - name: git diff --stat --staged
    abbr: sts
    snippet: diff --stat --staged
    global: true
    context: '^git\s'

  - name: git df --ignore-all-space
    abbr: dfi
    snippet: df --ignore-all-space
    global: true
    context: '^git\s'

  - name: git df --staged
    abbr: dfs
    snippet: df --staged
    global: true
    context: '^git\s'

  - name: git df --staged --ignore-all-space
    abbr: dfsi
    snippet: df --staged --ignore-all-space
    global: true
    context: '^git\s'

  # git fetch
  - name: git fetch
    abbr: f
    snippet: fetch
    global: true
    context: '^git\s'

  - name: git fetch upstream
    abbr: fu
    snippet: fetch upstream
    global: true
    context: '^git\s'

  # git log
  - name: git graph
    abbr: lg
    snippet: graph
    global: true
    context: '^git\s'

  # git pull
  - name: git pull
    abbr: pl
    snippet: pull
    global: true
    context: '^git\s'

  # git push
  - name: git push
    abbr: ps
    snippet: push
    global: true
    context: '^git\s'

  - name: git push -u origin BRANCH
    abbr: psu
    snippet: push -u origin $(git symbolic-ref --short HEAD)
    evaluate: true
    global: true
    context: '^git\s'

  - name: git push --force-with-lease
    abbr: -f
    snippet: --force-with-lease
    global: true
    context: '^git(\s+\S+)*\s+push\s'

  # git status
  - name: git status
    abbr: s
    snippet: status
    global: true
    context: '^git\s'

  # git switch
  - name: git switch
    abbr: sw
    snippet: switch
    global: true
    context: '^git\s'

  # git tag
  - name: git tag -l
    abbr: tags
    snippet: tag -l
    global: true
    context: '^git\s'

  # git current branch name
  - name: $(git symbolic-ref --short HEAD)
    abbr: B
    snippet: $(git symbolic-ref --short HEAD)
    global: true
    evaluate: true
    context: '^git\s'

  # lazygit
  - name: lazygit
    abbr: lg
    snippet: lazygit

  # docker
  - name: docker
    abbr: dok
    snippet: docker

  # docker compose
  - name: docker compose
    abbr: c
    snippet: compose
    global: true
    context: '^docker\s'

  # docker run
  - name: docker run -it
    abbr: ri
    snippet: run -it
    global: true
    context: '^docker\s'

  - name: docker run --rm
    abbr: rrm
    snippet: run --rm
    global: true
    context: '^docker\s'

  - name: docker run --rm -it
    abbr: rrmi
    snippet: run --rm -it
    global: true
    context: '^docker\s'

  # batgrep
  - name: batgrep
    abbr: brg
    snippet: batgrep

  # awk
  - name: awk '{ print $1 }'
    abbr: .1
    snippet: awk '{ print $1 }'

  - name: awk '{ print $2 }'
    abbr: .2
    snippet: awk '{ print $2 }'

  - name: awk '{ print $3 }'
    abbr: .3
    snippet: awk '{ print $3 }'

  - name: awk '{ print $4 }'
    abbr: .4
    snippet: awk '{ print $4 }'

  - name: awk '{ print $5 }'
    abbr: .5
    snippet: awk '{ print $5 }'
