.contexts:
  - &subcommand ^docker\s\S+$

abbrevs:
  # docker
  - name: d
    abbr: d
    snippet: docker

  # docker compose
  - name: docker c
    abbr: c
    snippet: compose
    global: true
    context: *subcommand

  # docker pull
  - name: docker pl
    abbr: pl
    snippet: pull
    global: true
    context: *subcommand

  # docker run
  - name: docker ri
    abbr: ri
    snippet: run -it
    global: true
    context: *subcommand

  - name: docker rrm
    abbr: rrm
    snippet: run --rm
    global: true
    context: *subcommand

  - name: docker rrmi
    abbr: rrmi
    snippet: run --rm -it
    global: true
    context: *subcommand

  # docker clean
  - name: docker clean
    abbr: clean
    snippet: container prune -f
    global: true
    context: *subcommand

  - name: docker cleani
    abbr: cleani
    snippet: image prune -f
    global: true
    context: *subcommand
