.contexts:
  - &global ^git\s
  - &subcommand ^git\s+\S+$
  - &bisect-command ^git(\s+\S+)*\s+bisect\s+\S+$
  - &push ^git(\s+\S+)*\s+push\s

abbrevs:
  # git
  - name: g
    abbr: g
    snippet: git
    if: |-
      [[ "$KEYS" != $'\r' ]]

  # git add
  - name: git aa
    abbr: aa
    snippet: add -vA
    global: true
    context: *subcommand

  # git bisect
  - name: git bisect b
    abbr: b
    snippet: bad
    global: true
    context: *bisect-command

  - name: git bisect g
    abbr: g
    snippet: good
    global: true
    context: *bisect-command

  - name: git bisect s
    abbr: s
    snippet: start
    global: true
    context: *bisect-command

  - name: git bi
    abbr: bi
    snippet: bisect
    global: true
    context: *subcommand

  # git branch
  - name: git b
    abbr: b
    snippet: branch
    global: true
    context: *subcommand

  # git commit
  - name: git c
    abbr: c
    snippet: commit
    global: true
    context: *subcommand

  - name: git cam
    abbr: cam
    snippet: commit --amend --no-edit
    global: true
    context: *subcommand

  - name: git cm
    abbr: cm
    snippet: commit -m '{}'
    global: true
    context: *subcommand

  - name: git cr
    abbr: cr
    snippet: commit --reuse-message={}
    global: true
    context: *subcommand

  - name: git C
    abbr: C
    snippet: cz
    global: true
    context: *subcommand

  - name: git fix
    abbr: fix
    snippet: commit --fixup={}
    global: true
    context: *subcommand

  # git cherry-pick
  - name: git cp
    abbr: cp
    snippet: cherry-pick
    global: true
    context: *subcommand

  # git diff
  - name: git st
    abbr: st
    snippet: diff --stat
    global: true
    context: *subcommand

  - name: git stat
    abbr: stat
    snippet: diff --stat
    global: true
    context: *subcommand

  - name: git stats
    abbr: stats
    snippet: diff --stat --staged
    global: true
    context: *subcommand

  - name: git sts
    abbr: sts
    snippet: diff --stat --staged
    global: true
    context: *subcommand

  - name: git dfi
    abbr: dfi
    snippet: df --ignore-all-space
    global: true
    context: *subcommand

  - name: git dfs
    abbr: dfs
    snippet: df --staged
    global: true
    context: *subcommand

  - name: git dfsi
    abbr: dfsi
    snippet: df --staged --ignore-all-space
    global: true
    context: *subcommand

  # git fetch
  - name: git f
    abbr: f
    snippet: fetch
    global: true
    context: *subcommand

  - name: git fu
    abbr: fu
    snippet: fetch upstream
    global: true
    context: *subcommand

  # git log
  - name: git lg
    abbr: lg
    snippet: graph
    global: true
    context: *subcommand

  # git pull
  - name: git pl
    abbr: pl
    snippet: pull
    global: true
    context: *subcommand

  # git push
  - name: git ps
    abbr: ps
    snippet: push
    global: true
    context: *subcommand

  - name: git pst
    abbr: pst
    snippet: push --tags
    global: true
    context: *subcommand

  - name: git push -f
    abbr: -f
    snippet: --force-with-lease
    global: true
    context: *push

  # git rebase
  - name: git q
    abbr: q
    snippet: rebase
    global: true
    context: *subcommand

  - name: git qq
    abbr: qq
    snippet: rebase --autosquash
    global: true
    context: *subcommand

  # git status
  - name: git s
    abbr: s
    snippet: status
    global: true
    context: *subcommand

  # git sync
  - name: git S
    abbr: S
    snippet: sync
    global: true
    context: *subcommand

  # git switch
  - name: git sw
    abbr: sw
    snippet: switch
    global: true
    context: *subcommand

  # git tag
  - name: git tags
    abbr: tags
    snippet: tag -l --sort=v:refname
    global: true
    context: *subcommand

  # git current branch name
  - name: git B
    abbr: B
    snippet: $(git symbolic-ref --short HEAD)
    global: true
    evaluate: true
    context: *global

  - name: git M
    abbr: M
    snippet: main
    global: true
    context: *global
    if: git show-ref --verify --quiet refs/heads/main

  - name: git M
    abbr: M
    snippet: master
    global: true
    context: *global

  - name: git D
    abbr: D
    snippet: develop
    global: true
    context: *global

  - name: git OB
    abbr: OB
    snippet: origin/$(git symbolic-ref --short HEAD)
    global: true
    evaluate: true
    context: *global

  - name: git O
    abbr: O
    snippet: origin
    global: true
    context: *global

  - name: git T
    abbr: T
    snippet: $tag
    global: true
    evaluate: true
    context: *global
    if: local tag; tag="$(git describe --abbrev=0 --tags @ 2>/dev/null)"

  - name: git T-
    abbr: T-
    snippet: $prev_tag
    global: true
    evaluate: true
    context: *global
    if: local prev_tag; prev_tag="$(git describe --abbrev=0 --tags @~ 2>/dev/null)"

  - name: git T+
    abbr: T+
    snippet: $(monkeywrench version inc --level=1 "$tag")
    global: true
    evaluate: true
    context: *global
    if: local tag; tag="$(git describe --abbrev=0 --tags @ 2>/dev/null)"

  - name: git T++
    abbr: T++
    snippet: $(monkeywrench version inc --level=2 "$tag")
    global: true
    evaluate: true
    context: *global
    if: local tag; tag="$(git describe --abbrev=0 --tags @ 2>/dev/null)"

  - name: git T!
    abbr: T!
    snippet: $(monkeywrench version inc --level=3 "$tag")
    global: true
    evaluate: true
    context: *global
    if: local tag; tag="$(git describe --abbrev=0 --tags @ 2>/dev/null)"

  - name: git U
    abbr: U
    snippet: upstream
    global: true
    context: *global
