.contexts:
  - &subcommand ^go\s+\S+$

abbrevs:
  # go build
  - name: go build -v
    abbr: b
    snippet: build -v
    global: true
    context: *subcommand

  # go generate
  - name: go generate -v
    abbr: g
    snippet: generate -v ./...
    global: true
    context: *subcommand

  # go run
  - name: go run -v .
    abbr: r
    snippet: run -v .{}
    global: true
    context: *subcommand

  # go test
  - name: go test ./...
    abbr: t
    snippet: test ./...
    global: true
    context: *subcommand
