abbrevs:
  # npm install
  - name: npm i
    abbr: i
    snippet: install
    global: true
    context: ^(git\s+exec\s+)?npm\s

  - name: npm -D
    abbr: -D
    snippet: --save-dev
    global: true
    context: ^(git\s+exec\s+)?npm\s+install\s

  # npm run
  - name: npm r
    abbr: r
    snippet: run
    global: true
    context: ^npm\s+r$

  - name: npm build
    abbr: build
    snippet: run build
    global: true
    context: ^npm\s+build$

  - name: npm fmt
    abbr: fmt
    snippet: run fmt
    global: true
    context: ^npm\s+fmt$

  # npm start
  - name: npm s
    abbr: s
    snippet: start
    global: true
    context: ^npm\s

  # npm test
  - name: npm t
    abbr: t
    snippet: test
    global: true
    context: ^npm\s
