.contexts:
  - &command ^(git\s+exec\s+)?\S+$
  - &subcommand ^(git\s+exec\s+)?(npm|pnpm)\s+\S+$
  - &install ^(git\s+exec\s+)?(npm|pnpm)\s+install\s

abbrevs:
  # npm install
  - name: npm i
    abbr: i
    snippet: install
    global: true
    context: *subcommand

  - name: npm -D
    abbr: -D
    snippet: --save-dev
    global: true
    context: *install

  # npm run
  - name: npm r
    abbr: r
    snippet: run
    global: true
    context: *subcommand

  - name: npm b
    abbr: b
    snippet: run build
    global: true
    context: *subcommand

  - name: npm d
    abbr: d
    snippet: run dev
    global: true
    context: *subcommand

  - name: npm f
    abbr: f
    snippet: run format
    global: true
    context: *subcommand
    if: monkeywrench node scripts --has="format"

  - name: npm f
    abbr: f
    snippet: run fmt
    global: true
    context: *subcommand

  - name: npm fmt
    abbr: fmt
    snippet: run format
    global: true
    context: *subcommand
    if: monkeywrench node scripts --has="format"

  - name: npm g
    abbr: g
    snippet: run generate
    global: true
    context: *subcommand
    if: monkeywrench node scripts --has="generate"

  - name: npm g
    abbr: g
    snippet: run gen
    global: true
    context: *subcommand

  - name: npm gen
    abbr: gen
    snippet: run generate
    global: true
    context: *subcommand
    if: monkeywrench node scripts --has="generate"

  - name: npm <script>
    abbr-pattern: ''
    snippet: run $abbr
    global: true
    evaluate: true
    context: *subcommand
    if: '[[ ! "$abbr" =~ "^(start|test)$" ]] && monkeywrench node scripts --has="$abbr"'

  # npm start
  - name: npm s
    abbr: s
    snippet: start
    global: true
    context: *subcommand

  # npm test
  - name: npm t
    abbr: t
    snippet: test
    global: true
    context: *subcommand

  # npm uninstall
  - name: npm un
    abbr: un
    snippet: uninstall
    global: true
    context: *subcommand

  # npm
  - name: <package-manager>
    abbr: npm
    snippet: $(monkeywrench node package-manager)
    global: true
    evaluate: true
    context: *command

  - name: n
    abbr: n
    snippet: $(monkeywrench node package-manager)
    global: true
    evaluate: true
    context: *command

  # npx
  - name: <npx>
    abbr-pattern: ''
    snippet: npx $abbr
    evaluate: true
    if: >
      (( ! ${+commands[$abbr]} && ! ${+functions[$abbr]} && ! ${+aliases[$abbr]} && ! ${+builtins[$abbr]} ))
      && [[ -x "$(monkeywrench node toplevel --root)/node_modules/.bin/$abbr" ]]

