abbrevs:
  # npm install
  - name: npm i
    abbr: i
    snippet: install
    global: true
    context: ^(git\s+exec\s+)?(npm|pnpm)\s

  - name: npm -D
    abbr: -D
    snippet: --save-dev
    global: true
    context: ^(git\s+exec\s+)?(npm|pnpm)\s+install\s

  # npm run
  - name: npm r
    abbr: r
    snippet: run
    global: true
    context: ^(npm|pnpm)\s+\S+$

  - name: npm b
    abbr: b
    snippet: run build
    global: true
    context: ^(npm|pnpm)\s+\S+$

  - name: npm d
    abbr: d
    snippet: run dev
    global: true
    context: ^(npm|pnpm)\s+\S+$

  - name: npm f
    abbr: f
    snippet: run fmt
    global: true
    context: ^(npm|pnpm)\s+\S+$

  - name: npm <script>
    abbr-pattern: ''
    snippet: run $abbr
    global: true
    evaluate: true
    context: ^npm\s+\S+$
    if: '[[ ! "$abbr" =~ "^(start|test)$" ]] && monkeywrench node scripts --has "$abbr"'

  # npm start
  - name: npm s
    abbr: s
    snippet: start
    global: true
    context: ^(npm|pnpm)\s

  # npm test
  - name: npm t
    abbr: t
    snippet: test
    global: true
    context: ^(npm|pnpm)\s

  # npm
  - name: <package-manager>
    abbr: npm
    snippet: $(monkeywrench node package-manager)
    global: true
    evaluate: true
    context: ^(git\s+exec\s+)?\S+$
