message:
  items:
    - name: type
      # description: Select the type of change that you're committing
      description: コミットする変更タイプを選択
      required: true
      form: select
      options:
        - name: feat
          # description: A new feature
          description: 新機能
        - name: fix
          # description: A bug fix
          description: バグ修正
        - name: docs
          # description: Documentation only changes
          description: ドキュメントのみの変更
        - name: style
          # description: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
          description: フォーマットの変更 (コードの動作に影響しないスペース、フォーマット、セミコロンなど)
        - name: refactor
          # description: A code change that neither fixes a bug nor adds a feature
          description: リファクタリングのための変更 (機能追加やバグ修正を含まない)
        - name: perf
          # description: A code change that improves performance
          description: パフォーマンスの改善のための変更
        - name: test
          # description: Adding missing tests or correcting existing tests
          description: 不足テストの追加や既存テストの修正
        - name: build
          # description: "Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"
          description: "ビルドシステムや外部依存に関する変更 (スコープ例: gulp, broccoli, npm)"
        - name: ci
          # description: "Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)"
          description: "CI用の設定やスクリプトに関する変更 (スコープ例: Travis, Circle, BrowserStack, SauceLabs)"
        - name: chore
          # description: Other changes that don't modify src or test files
          description: その他の変更 (ソースやテストの変更を含まない)
        - name: revert
          # description: Reverts a previous commit
          description: 以前のコミットに復帰

    - name: scope
      # description: What is the scope of this change (e.g. component or file name)
      description: "変更内容のスコープ (例:コンポーネントやファイル名): (enterでスキップ)"
      form: input

    - name: subject
      # description: Write a short, imperative tense description of the change
      description: 変更内容を要約した本質的説明
      required: true
      form: input

    - name: body
      # description: Provide a longer description of the change
      description: "変更内容の詳細: (enterでスキップ)"
      form: input

    - name: breakingChange
      # description: Describe the breaking changes if exist
      description: "破壊的変更についての記述: (enterでスキップ)"
      form: input

    - name: issue
      # description: 'Add issue references (e.g. "fix #123", "re #123".)'
      description: '関連issueを追記 (例:"fix #123", "re #123"): (enterでスキップ)'
      form: input

  template: "<%- type %><% if (scope) { %>(<%- scope %>)<% } %>: <%- subject %><% if (body) { %>\n\n<%- body %><% } %><% if (breakingChange) { %>\n\nBREAKING CHANGE: <%- breakingChange %><% } %><% if (issue) { %>\n\n<%- issue %><% } %>"
