os:
  linux:
    background: 33
  mac:
    background: 33
  windows:
    background: 33

git_user:
  background: 75

time:
  format: "\uf017 %H:%M:%S"

duration:
  background: 242

segments:
  - - os
    - user
    - directory
    - git_repo
    - git_user
  - - duration
    - status
