name: {{ .Filename | Abs | Dir | Base }}
root: {{ .Filename | Abs | Dir }}

startup_window: main
startup_page: 1

windows:
  - main:
      layout: even-horizontal
      panes:
        - vim
        -
  - server: npm start
