name: Format

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clang-Format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '16'
