disableStartupPopups: true
quitOnTopLevelReturn: true
notARepository: 'skip'
git:
  disableForcePushing: true
gui:
  showFileTree: true
  showRandomTip: false
keybinding:
  commits:
    viewResetOptions: 'G'
