disableStartupPopups: true
quitOnTopLevelReturn: true
notARepository: 'skip'
git:
  disableForcePushing: true
  paging:
    colorArg: always
    useConfig: true
  parseEmoji: true
gui:
  showFileTree: true
  showRandomTip: false
os:
  openCommand: "code --goto {{filename}}"
keybinding:
  commits:
    viewResetOptions: 'G'
