disableStartupPopups: true
quitOnTopLevelReturn: true
promptToReturnFromSubprocess: false
notARepository: quit

git:
  autoFetch: false
  disableForcePushing: true
  parseEmoji: true
  paging:
    colorArg: always
    pager: delta --paging=never
  log:
    showGraph: always

gui:
  language: ja
  timeFormat: 2006-01-02 15:04
  showRandomTip: false
  showBottomLine: false
  showIcons: true

os:
  openCommand: "code --goto -- {{filename}}:{{line}}"
  editCommand: "nvim"
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"

keybinding:
  commits:
    viewResetOptions: G
  branches:
    rebaseBranch: R
    renameBranch: r

customCommands:
  - key: <c-f>
    command: git sync
    context: global
    subprocess: true

  - key: C
    command: git cz
    context: files
    subprocess: true

  - key: r
    prompts:
      - key: Message
        type: input
        title: "Rename stash: {{.SelectedStashEntry.RefName}}"
        initialValue: "{{.SelectedStashEntry.Name}}"
    command: >-
      git stash drop {{.SelectedStashEntry.RefName}}
      | sed -E 's/.*\(([0-9a-f]+)\).*/\1/'
      | xargs git stash store -m {{.Form.Message | quote}}
    context: stash
