name: macOS

on: [push]

jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: bash ./scripts/setup.bash
